[features]
seeds = false
skip-lint = false
[programs.localnet]
safe_transfer = "BpCbo5wS53SLmnppnPeZCi271V87s4MkiT9YijMLxC36"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/linktel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
